name: random_color
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
 
  flutter_riverpod: ^2.4.0
  get_it: ^7.6.4
  riverpod: ^2.4.0
  solid_lints: ^0.0.19

dev_dependencies:
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true